### ISSUE TITLE
Apply Callosum RPC

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai-manager#79]
Ref: https://github.com/lablup/callosum

NOTE: The concept of keypairs in this issue is about manager-agent authentication -- not for authentication of gateway API requests.

Related: lablup/backend.ai-agent#63

In the manager side:

### Phase 1:
* [x] Replace `aiozmq.rpc` with Callosum

### Phase 2 (manager-agent tunneling via public networks):
* [ ] Add config entries for the server public/private keypair
* [ ] Implement a callosum authenticator interface to check if the agent public key is the registered one via scaling groups DB.
* [ ] Extend DB models
  - Each scaling group stores an "agent" public key generated by `zmq.curve_keypair()`.
  - Each scaling group may have different authentication modes: "local" and "curve". The "local" mode is for agent deployments in the same LAN where the manager resides (which does not perform any authentication), while the "curve" mode is for remote agents connected via the public Internet.
  - When generating a new agent keypair, the server should NOT store the private key -- we should return it only once and forget afterwards. (Keep in mind that debug logs should not contain it!)
* [ ] A new auth-required API to query the public key of the manager server so that users can setup their own agents easier?

**Comment by achimnol** [comment]
Now we have the first public release of Callosum (v0.9).
Let's adopt it.

**Comment by achimnol** [comment]
The phase 2 will be handled in lablup/backend.ai#90.
